# Generated by Django 3.1.3 on 2020-12-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('ticker', models.CharField(max_length=300)),
                ('buy_price', models.FloatField()),
                ('number_of_shares', models.IntegerField()),
            ],
        ),
    ]
